# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lamport.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='lamport.proto',
  package='com.npr',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rlamport.proto\x12\x07\x63om.npr\"\x92\x02\n\x07Lamport\x12\x32\n\x0cmessage_type\x18\x01 \x01(\x0e\x32\x1c.com.npr.Lamport.MessageType\x12\r\n\x05\x63lock\x18\x02 \x01(\x03\x12\x11\n\tid_sender\x18\x03 \x01(\x05\x12\x13\n\x0bid_receiver\x18\x04 \x01(\x05\"\x9b\x01\n\x0bMessageType\x12\x13\n\x0fREQUEST_INITIAL\x10\x00\x12\x11\n\rREPLY_INITIAL\x10\x01\x12\x13\n\x0fRELEASE_INITIAL\x10\x02\x12\x0b\n\x07REQUEST\x10\x03\x12\t\n\x05REPLY\x10\x04\x12\x0b\n\x07RELEASE\x10\x05\x12\t\n\x05SLEEP\x10\x06\x12\x08\n\x04WAKE\x10\x07\x12\x15\n\x11\x45ND_COMMUNICATION\x10\x08\x62\x06proto3'
)



_LAMPORT_MESSAGETYPE = _descriptor.EnumDescriptor(
  name='MessageType',
  full_name='com.npr.Lamport.MessageType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='REQUEST_INITIAL', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REPLY_INITIAL', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RELEASE_INITIAL', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REQUEST', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='REPLY', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='RELEASE', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='SLEEP', index=6, number=6,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='WAKE', index=7, number=7,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='END_COMMUNICATION', index=8, number=8,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=146,
  serialized_end=301,
)
_sym_db.RegisterEnumDescriptor(_LAMPORT_MESSAGETYPE)


_LAMPORT = _descriptor.Descriptor(
  name='Lamport',
  full_name='com.npr.Lamport',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message_type', full_name='com.npr.Lamport.message_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='clock', full_name='com.npr.Lamport.clock', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id_sender', full_name='com.npr.Lamport.id_sender', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='id_receiver', full_name='com.npr.Lamport.id_receiver', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _LAMPORT_MESSAGETYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=301,
)

_LAMPORT.fields_by_name['message_type'].enum_type = _LAMPORT_MESSAGETYPE
_LAMPORT_MESSAGETYPE.containing_type = _LAMPORT
DESCRIPTOR.message_types_by_name['Lamport'] = _LAMPORT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Lamport = _reflection.GeneratedProtocolMessageType('Lamport', (_message.Message,), {
  'DESCRIPTOR' : _LAMPORT,
  '__module__' : 'lamport_pb2'
  # @@protoc_insertion_point(class_scope:com.npr.Lamport)
  })
_sym_db.RegisterMessage(Lamport)


# @@protoc_insertion_point(module_scope)
